### ISSUE TITLE
How can I correctly download a file?

### ISSUE THREAD

**Issue by JoeDawson** [internalsystemerror/php-soundcloud#8]
Hello,

I'm attempting to save a file locally on my server using the download() method this wrapper provides.

Here's what I currently have;

```php
$soundcloud = new SoundCloud(
	getenv('SC_CLIENT_ID'),
	getenv('SC_CLIENT_SECRET')
);

$tracks = json_decode($soundcloud->get('users/{myId}/favorites'));

foreach($tracks as $track) {

	if($track->downloadable) {

		$track = $soundcloud->download($track->id);

		// How can I save $track - to my server?
	}
}
```

As you can see, I'm fetching a user (my owns) favourites - checking to see if a download if available, this is where I'd like to download it to my server.

How can I achieve this?

**Comment by internalsystemerror** [comment]
This repository is a mirror to mptre/php-soundcloud, so I recommend you also ask your question there. I've not actually tried to use this functionality, however, if $track is a file resource, you could try using fwrite(), otherwise if it is data, then file_put_contents() would probably work?

**Comment by JoeDawson** [comment]
Thank you for your response @internalsystemerror, I unfortunately switched to another package - only due to it having documentation for saving the file (that's all I really need from the API). 

https://github.com/njasm/soundcloud#file-download

Again - appreciate the response, consider this closed.
